#!/bin/bash
set -e

if git diff --cached --quiet; then
  echo "No staged changes found."
  exit 0
fi

npx alex-c-line check-lockfile-version-discrepancy

npm run format
npm run lint

git update-index --again
