#!/bin/bash
set -e

if git diff --cached --quiet; then
  echo "No staged changes found."
  exit 1
fi

npx alex-c-line check-lockfile-version-discrepancy

npm run format
npm run lint

# Warn in the console if there are source code changes but version number has not been changed
if !(git diff --cached --quiet "src/*"); then
  oldPackageVersion=$(git show origin/main:package.json | jq -r ".version")
  if [[ "$oldPackageVersion" == "$newPackageVersion" ]]; then
      IFS='.' read -r major minor patch <<< "$oldPackageVersion"
      newMajorPackageVersion="$((major + 1)).0.0"
      newMinorPackageVersion="$major.$((minor + 1)).0"
      newPatchPackageVersion="$major.$minor.$((patch + 1))"

      echo "⚠️ WARNING: Source code changes found but version has not been updated. Please run one of the following:"
      echo "- \`npm run change-major\` (v$oldPackageVersion -> v$newMajorPackageVersion)"
      echo "- \`npm run change-minor\` (v$oldPackageVersion -> v$newMinorPackageVersion)"
      echo "- \`npm run change-patch\` (v$oldPackageVersion -> v$newPatchPackageVersion)"
  fi
fi

git update-index --again
